bucket          = "sg-ssd-devics-tfstate"
region          = "eu-west-2"
key             = "document-upload/static-website/nonprod.tfstate"
#dynamodb_table  = "sg-ssd-ce-tfstatelock"
profile         = ""